import { activityEvents, automationConfigs, businessTargets, industries, notifications, productionBatches, promptVersions, proposals } from "../drizzle/schema";
import { getDb } from "./db";

const WORLD_BANK = "https://openknowledge.worldbank.org/entities/publication/6ad606a5-3085-47eb-a360-83fa3d38ea04";
const INVESTMENT = "https://myanmarcgla.org/index.php/commercial/investment-opportunities";
const DIGITAL = "https://datareportal.com/reports/digital-2026-myanmar";
const CITY_MALL = "https://www.citymall.com.mm/citymall/my/%E1%80%95%E1%80%85%E1%80%B9%E1%80%85%E1%80%8A%E1%80%BA%E1%80%B8%E1%80%A1%E1%80%99%E1%80%BB%E1%80%AD%E1%80%AF%E1%80%B8%E1%80%A1%E1%80%85%E1%80%AC%E1%80%B8%E1%80%99%E1%80%BB%E1%80%AC%E1%80%B8/%E1%80%85%E1%80%AC%E1%80%B8%E1%80%9E%E1%80%B1%E1%80%AC%E1%80%80%E1%80%BA%E1%80%80%E1%80%AF%E1%80%94%E1%80%BA%E1%80%95%E1%80%85%E1%80%B9%E1%80%85%E1%80%8A%E1%80%BA%E1%80%B8%E1%80%99%E1%80%BB%E1%80%AC%E1%80%B8/c/id01?q=%3Abestselling&page=169";

export const INDUSTRY_SEED = [
  ["fnb", "Food & Beverage / FMCG", "အစားအသောက်နှင့် FMCG", "Tier 1", 90, 94, 88, 61, "High-frequency consumer need with clear retail, experiential, creator and CRM pathways.", "Sampling, sensory/ASMR, retail activation, seasonal gifting, creator commerce, CRM.", CITY_MALL, "Public Myanmar-language retail catalogue provides current product and category visibility; score is ZYNTH’s transparent pitch-priority model, not a market-size forecast."],
  ["retail", "Retail & E-commerce", "လက်လီရောင်းဝယ်ရေး", "Tier 1", 88, 92, 90, 61, "Digital discovery and in-store conversion can be joined through source-coded retail programmes.", "Pop-up, retail theatre, paid funnel, loyalty, social commerce, festive trade.", CITY_MALL, "Retail catalogue indicates local-language online category infrastructure. Validate each retailer’s commercial availability before outreach."],
  ["financial", "Financial Services & Fintech", "ငွေကြေးဝန်ဆောင်မှုနှင့် Fintech", "Tier 1", 87, 84, 86, 78, "High-need trust and education category; use careful compliance and responsible communications.", "SME forum, financial literacy, CRM reactivation, merchant activation, product education.", WORLD_BANK, "World Bank flags macro/financial constraints. Score reflects strategic campaign opportunity subject to legal and compliance approval."],
  ["telecom-tech", "Telecom, Technology & Digital Services", "ဆက်သွယ်ရေးနှင့် နည်းပညာ", "Tier 1", 86, 89, 95, 73, "Large connected audience supports mobile-first service, device, enterprise and digital-adoption programmes.", "Innovation exhibition, product demo, social challenge, B2B ABM, retail activation.", DIGITAL, "DataReportal reports 39.8m internet users and 62.5m mobile connections in late 2025; figures are planning context, not reach guarantees."],
  ["hospitality", "Hospitality, Tourism & MICE", "ဟိုတယ်၊ ခရီးသွားနှင့် MICE", "Tier 1", 82, 88, 79, 74, "Q4 events, staycation, MICE, community and advance-booking pathways need strong local operational validation.", "Press preview, executive forum, cultural activation, gala, creator-led itinerary, CRM.", INVESTMENT, "Official investment information identifies tourism and hospitality opportunities; assess safety, venue and operating conditions case-by-case."],
  ["beauty", "Beauty, Wellness & Personal Care", "အလှအပနှင့် Wellness", "Tier 1", 81, 91, 89, 62, "Sensory demonstration and repeat-purchase mechanics create strong agency-fit opportunities.", "ASMR, retail pop-up, sampling, masterclass, creator content, loyalty.", CITY_MALL, "Tier represents campaign suitability under the ZYNTH model; validate brand/product compliance and retailer inventory before pitching."],
  ["automotive-ev", "Automotive, Mobility & EV", "မော်တော်ယာဉ်၊ Mobility နှင့် EV", "Tier 2", 79, 83, 75, 76, "High-consideration category where test-drive, dealer enablement and education can create qualified intent.", "Roadshow, dealer event, test drive, ownership clinic, fleet ABM.", INVESTMENT, "Official sector opportunity material names automotive/land machinery manufacturing; customer, charging and distributor reality requires local validation."],
  ["education", "Education, Training & EdTech", "ပညာရေး၊ သင်တန်းနှင့် EdTech", "Tier 2", 78, 88, 84, 64, "Family decision cycles, intake, professional training and employer relevance create recurring communication needs.", "Open house, masterclass, education fair, content series, CRM reactivation.", INVESTMENT, "Education services are identified in several regional priorities. Score is for marketing opportunity, not institutional ranking."],
  ["healthcare", "Healthcare, Clinics & HealthTech", "ကျန်းမာရေး၊ Clinic နှင့် HealthTech", "Tier 2", 77, 78, 73, 80, "Trust, appointment conversion and compliant patient education are core campaign opportunities.", "Screening programme, patient education, appointment funnel, community activation.", INVESTMENT, "Official sector material identifies private healthcare opportunities; all claims and audience engagement require medical/legal review."],
  ["real-estate", "Real Estate, Housing & Urban Development", "အိမ်ခြံမြေ၊ Housing နှင့် Urban Development", "Tier 2", 76, 80, 72, 81, "Open-house and referral systems can create qualified site-visit pathways where inventory and legal status are clear.", "Show-unit experience, broker enablement, referral open house, paid lead funnel.", INVESTMENT, "Official source cites affordable housing and urbanisation opportunities; campaign score does not assess individual developments."],
  ["manufacturing", "Manufacturing, Industrial & B2B", "ကုန်ထုတ်လုပ်မှုနှင့် B2B", "Tier 2", 80, 78, 68, 77, "Distributor, procurement, product-proof and account-based marketing needs are strong, with operational risk sensitivity.", "Trade show, distributor workshop, B2B content, ABM, plant/open-house programme.", INVESTMENT, "Official source identifies value-added manufacturing, agro-processing and industrial services. Validate import, energy and logistics assumptions."],
  ["entertainment", "Entertainment, Media & Culture", "ဖျော်ဖြေရေး၊ Media နှင့် Culture", "Tier 2", 74, 86, 88, 69, "Audience participation, sponsorship and commercial-content pathways can create differentiated brands.", "Festival, sponsorship, branded content, commercial video, fan/community programme.", DIGITAL, "Digital-adoption evidence supports mobile content context; rights, talent, venue and safety terms must be confirmed."],
  ["logistics", "Logistics, Transport & Supply Chain", "Logistics နှင့် Supply Chain", "Tier 3", 76, 72, 66, 81, "B2B visibility, route trust and trade education offer opportunities but depend on operating constraints.", "Executive forum, ABM, trade roadshow, client education, employer brand.", INVESTMENT, "Official source identifies logistics infrastructure. Score is a planning priority, not a sector investment recommendation."],
  ["agrifood", "Agriculture, Agrifood & Fisheries", "စိုက်ပျိုးရေး၊ Agrifood နှင့် ငါးလုပ်ငန်း", "Tier 3", 79, 71, 55, 76, "Value-added processing, market access, education and community programmes are relevant agency routes.", "Trade show, farmer education, community programme, value-chain storytelling.", INVESTMENT, "Official material lists agriculture, aquaculture, cold chain and value-added processing opportunities."],
  ["energy", "Energy, Power & Sustainability", "စွမ်းအင်၊ Power နှင့် Sustainability", "Tier 3", 78, 69, 59, 84, "High-stakes stakeholder and B2B communication needs require strict diligence and approvals.", "Stakeholder forum, B2B summit, community engagement, employer brand.", INVESTMENT, "Official opportunity source identifies power and renewables; no project, licence or technical claim is assumed."],
  ["ngo", "NGO, Social Impact & Development", "NGO၊ လူမှုအကျိုးသက်ရောက်မှု", "Tier 3", 71, 77, 74, 70, "Community participation, donor, volunteer and awareness workflows can use evidence-led storytelling.", "Community programme, documentary series, donor funnel, workshop, impact report.", WORLD_BANK, "World Bank highlights household vulnerability. Campaign work must protect participants and avoid extractive storytelling."],
  ["corporate", "Corporate, Employer Brand & Professional Services", "Corporate နှင့် Employer Brand", "Tier 3", 70, 80, 77, 70, "Recruitment, internal culture and B2B trust-building can be managed through structured production workflows.", "Employer brand video, executive forum, recruitment campaign, content series.", WORLD_BANK, "Business environment uncertainty makes credible internal/external trust-building relevant, subject to organisation-specific research."],
  ["luxury", "Luxury, Lifestyle & Premium Experience", "Luxury နှင့် Premium Lifestyle", "Tier 4", 62, 75, 71, 77, "Selective high-touch experiences can fit verified premium audiences and partners.", "Private preview, gala, VIP salon, luxury pop-up, concierge CRM.", DIGITAL, "Digital indicators provide broad channel context only; audience size and commercial viability require client-specific validation."],
  ["insurance", "Insurance & Protection", "အာမခံနှင့် Protection", "Tier 4", 65, 72, 70, 82, "Education, trust and partner distribution could be relevant if compliant and properly approved.", "Financial literacy, partner activation, content series, CRM.", WORLD_BANK, "Financial-sector constraints and consumer vulnerability require conservative, compliance-first planning."],
  ["sports", "Sports, Lifestyle & Community", "အားကစား၊ Lifestyle နှင့် Community", "Tier 4", 63, 74, 77, 66, "Participation-based brand platforms can be useful when sponsorship rights and safeguarding are clear.", "Sponsorship, tournament activation, community programme, social challenge.", DIGITAL, "Digital source supports content distribution context; this is a campaign-fit score rather than market-size evidence."],
] as const;

const MASTER_PROMPT = `ZYNTH Myanmar Proposal & Commercial Production Master Prompt\n\nFor one rotated Myanmar industry, create 10 materially different proposal concepts. For each concept, generate a full-English Word proposal and an English–Myanmar hybrid Word proposal. Research public sources first, cover September–December seasonal/sponsorship opportunities where relevant, provide a distinct creative title, integrated campaign plan, MMK Lean/Recommended/Flagship budgets, explicit ROI scenarios, approvals, and sources. For physical events create labelled sketch and four-view client design packages; for digital campaigns create experience storyboards. Add a commercial-video extension with tagline, storyline, shot-by-shot storyboard, production-house/talent/client workflow, pre-production through delivery gate plan, budget assumptions and usage-rights approvals. Save a source manifest; update Google Drive and GitHub together; post exact batch, document, sync and error status to the ZYNTH command center.`;

export async function ensureCommandCenterSeed() {
  const db = await getDb();
  if (!db) return;
  await db.insert(automationConfigs).values({ code: "zynth-bilingual-two-hour-cycle", cronExpression: "0 0 */2 * * *", isEnabled: 1, lastStatus: "Queued" }).onDuplicateKeyUpdate({ set: { cronExpression: "0 0 */2 * * *" } });
  const existing = await db.select({ id: industries.id }).from(industries).limit(1);
  if (existing.length) return;

  await db.insert(industries).values(INDUSTRY_SEED.map(([code, name, nameMyanmar, tier, marketPotentialScore, pitchReadinessScore, digitalReadinessScore, operationalRiskScore, opportunitySummary, campaignFit, sourceUrl, sourceNote]) => ({
    code, name, nameMyanmar, tier, marketPotentialScore, pitchReadinessScore, digitalReadinessScore, operationalRiskScore, opportunitySummary, campaignFit, sourceUrl, sourceNote,
  })));
  const seededIndustries = await db.select().from(industries);
  const byCode = new Map(seededIndustries.map(item => [item.code, item.id]));
  const fnb = byCode.get("fnb")!;
  const financial = byCode.get("financial")!;
  const hospitality = byCode.get("hospitality")!;

  await db.insert(businessTargets).values([
    { industryId: fnb, name: "City Mall / City Mart food category", nameMyanmar: "City Mall / City Mart အစားအသောက်အမျိုးအစား", targetClass: "Public retail ecosystem candidate", opportunityScore: 94, pitchAngle: "Retail activation, category storytelling, seasonal bundles and source-coded conversion.", sourceUrl: CITY_MALL, verificationStatus: "Public catalogue verified; commercial contact and availability TBC", nextAction: "Research official corporate contact and category sponsorship policy." },
    { industryId: fnb, name: "Popy / Pa Pa / Yummy snack brands", nameMyanmar: "Popy / Pa Pa / Yummy snack brands", targetClass: "Publicly listed sensory-product candidates", opportunityScore: 90, pitchAngle: "ASMR-led sensory content, sampling and youth retail activation.", sourceUrl: CITY_MALL, verificationStatus: "Public catalogue presence verified; ownership and campaign contact TBC", nextAction: "Confirm brand owner and distribution contact from first-party source." },
    { industryId: fnb, name: "Feel Myanmar Food", nameMyanmar: "Feel Myanmar Food", targetClass: "Publicly listed food-service candidate", opportunityScore: 86, pitchAngle: "Comfort-food content, seasonal menu, delivery and customer-retention concept.", sourceUrl: CITY_MALL, verificationStatus: "Public catalogue product presence verified; commercial scope TBC", nextAction: "Verify official company channel before outreach." },
    { industryId: financial, name: "Financial-services research queue", nameMyanmar: "Financial-services research queue", targetClass: "Sector prioritisation queue", opportunityScore: 84, pitchAngle: "Compliance-first financial education, SME activation and CRM retention.", sourceUrl: WORLD_BANK, verificationStatus: "Industry opportunity only; no brand/contact claim", nextAction: "Add first-party institution sources and compliance review before pitching." },
    { industryId: hospitality, name: "Hospitality/MICE research queue", nameMyanmar: "Hospitality/MICE research queue", targetClass: "Sector prioritisation queue", opportunityScore: 83, pitchAngle: "MICE preview, corporate stays, seasonal event and advance-booking flows.", sourceUrl: INVESTMENT, verificationStatus: "Industry opportunity only; no venue availability claim", nextAction: "Add verified venue/hotel public package sources before outreach." },
  ]);

  const now = new Date("2026-08-20T08:00:00.000Z");
  const batch = await db.insert(productionBatches).values({
    batchCode: "ZYNTH-2026-08-20-FNB-BILINGUAL", industryId: fnb, scheduledAt: now, completedAt: new Date("2026-08-20T12:00:00.000Z"), status: "Complete", proposalCount: 10, documentCount: 20, videoConceptCount: 0, driveSyncStatus: "Synced", githubSyncStatus: "Synced", syncRetryStatus: "Not needed", driveFolderUrl: "https://drive.google.com/drive/folders/1U0G9j_EG_L0vcm679CDR1CEGDtMNlD64", githubUrl: "https://github.com/zanezynthbrain/zynth-brain/tree/main/daily_proposals/2026-08-20_FNB_Bilingual", githubCommit: "ee32a4d",
  });
  const batchId = Number((batch as { insertId?: number }).insertId ?? 1);
  const fnbProposals = [
    ["The First Crunch", "ပထမဆုံး ကြွပ်ရွသံ", "Experiential sampling roadshow + social-first ASMR challenge", "8–20 September 2026", 32000000, 56000000, 92000000, "+0%", "+60%", "+100%", "September back-to-routine sampling window; sponsorship is optional and unconfirmed.", "Use a source-coded sensory sampling path to move attention into retail redemption."],
    ["Rain, Steam, Repeat", "မိုး၊ အငွေ့၊ ထပ်မံခံစား", "Delivery-partner pop-up + comfort-food creator content series", "15–30 September 2026", 28000000, 48000000, 78000000, "+0%", "+60%", "+100%", "September monsoon comfort-food planning window, subject to weather and partner confirmation.", "Build a rain-day comfort ritual with voucher redemption and consented repeat-order follow-up."],
    ["Lights, Bites, Together", "မီးရောင်နဲ့ အရသာ—အတူတကွ", "Thadingyut retail activation + family gifting campaign", "16–27 October 2026", 50000000, 88000000, 145000000, "+0%", "+60%", "+100%", "Thadingyut planning relies on public holiday timing; retail hours and sponsorship remain TBC.", "Make family gifting a useful retail-bundle and loyalty-acquisition action."],
    ["The Pantry of Possibility", "အရသာဖြစ်နိုင်ခြေများ၏ စားစရာခန်း", "B2B exhibition pavilion + distributor workshop", "20–31 October 2026", 76000000, 135000000, 215000000, "-5%", "+55%", "+95%", "Late-October trade-show readiness window; organiser inventory requires validation.", "Convert product proof into distributor meetings and pilot-store actions."],
    ["Taste That Travels", "ခရီးသွားသော အရသာ", "Exhibition sponsorship + export/distributor ABM", "30 October–1 November 2026", 90000000, 158000000, 248000000, "-5%", "+55%", "+95%", "Proposed FoodBev/Retail Sourcing Expo timing; date, venue and sponsorship rights are TBC.", "Use a tasting passport and buyer appointment flow to create qualified B2B demand."],
    ["First Light, First Bite", "အလင်းဦးနဲ့ ပထမအရသာ", "Cultural night-market activation + community food programme", "20–24 November 2026", 55000000, 98000000, 160000000, "+0%", "+55%", "+95%", "Tazaungdaing planning window requires cultural, township and permit review.", "Share local-maker stories through a taste trail and community contribution choice."],
    ["The Sound of Home", "အိမ်ရဲ့ အသံ", "Influencer-led ASMR content relay + retail endcap", "10–30 November 2026", 24000000, 44000000, 72000000, "+0%", "+60%", "+105%", "November content platform not tied to an unverified special date.", "Transform familiar food sounds into creator-coded purchase and opt-in signals."],
    ["Made for the Table", "စားပွဲအတွက် ဖန်တီးထားသည်", "Local-ingredient community programme + retail story series", "1–6 December 2026", 38000000, 68000000, 110000000, "+0%", "+55%", "+100%", "National Day local-production content window; do not make unsupported provenance claims.", "Link source-aware stories to recipe saves, product bundles and retailer referrals."],
    ["Sip the Year Brighter", "နှစ်သစ်ကို ပိုလင်းလက်စွာ သောက်စို့", "Beverage sponsorship + responsible micro-festival", "10–25 December 2026", 72000000, 128000000, 205000000, "-5%", "+50%", "+90%", "Year-end/Christmas window; any alcohol activity requires distinct age-gating and legal review.", "Create a responsible inclusive toast with retail conversion and transport-safe exit."],
    ["The Last Good Bite", "နှစ်ကုန်ရဲ့ အကောင်းဆုံး တစ်ကိုက်", "CRM/reactivation + retail loyalty closeout", "26–31 December 2026", 18000000, 34000000, 60000000, "+0%", "+65%", "+110%", "Year-end closeout based on retailer/client trading calendar, not invented urgency.", "Re-activate real buyers with a useful reward, referral and January return cue."],
  ] as const;
  await db.insert(proposals).values(fnbProposals.map(([title, titleMyanmar, campaignType, seasonalWindow, budgetLeanMmk, budgetRecommendedMmk, budgetFlagshipMmk, roiConservative, roiBase, roiUpside, seasonalRationale, conceptSummary], index) => ({
    batchId, industryId: fnb, proposalCode: `ZYNTH-FNB-20260820-${String(index + 1).padStart(2, "0")}`, title, titleMyanmar, campaignType, seasonalWindow, languageStatus: "Both" as const, stage: "Draft" as const, budgetLeanMmk, budgetRecommendedMmk, budgetFlagshipMmk, roiConservative, roiBase, roiUpside, seasonalRationale, conceptSummary, documentEnglishUrl: "https://drive.google.com/drive/folders/1U0G9j_EG_L0vcm679CDR1CEGDtMNlD64", documentHybridUrl: "https://drive.google.com/drive/folders/1U0G9j_EG_L0vcm679CDR1CEGDtMNlD64", owner: "ZYNTH Strategy",
  })));
  await db.insert(promptVersions).values({ name: "ZYNTH Proposal & Commercial Production Master Prompt", version: "2.0.0", content: MASTER_PROMPT, changeNote: "Adds bilingual outputs, commercial-video workflow, production gates and command-center status callback.", isActive: 1 });
  await db.insert(activityEvents).values([
    { entityType: "batch", entityId: batchId, title: "F&B bilingual proposal batch published", detail: "10 campaign concepts, 20 Word documents and 18 design/storyboard assets recorded with Drive and GitHub confirmation.", priority: "High", actor: "ZYNTH Production Cycle", occurredAt: new Date("2026-08-20T12:00:00.000Z") },
    { entityType: "system", title: "CEO command-center schema initialized", detail: "Industry intelligence, proposal, video, batch, notification and prompt governance data model is ready for live records.", priority: "Normal", actor: "ZYNTH Command Center" },
    { entityType: "prompt", title: "Master prompt version 2.0.0 activated", detail: "The prompt now instructs full commercial proposals, storyboards and production workflow tracking.", priority: "Normal", actor: "ZYNTH Strategy" },
  ]);
  await db.insert(notifications).values([
    { type: "batch_published", title: "New bilingual F&B batch is available", detail: "20 proposal documents and supporting design assets were recorded as synchronized to Drive and GitHub.", priority: "High", isRead: 0 },
    { type: "seasonal_deadline", title: "September planning window is approaching", detail: "Prioritise supplier quotation, location and partner validation for September campaign concepts.", priority: "High", isRead: 0, dueAt: new Date("2026-09-01T00:00:00.000Z") },
    { type: "integration", title: "Dashboard callback activation is pending publication", detail: "The scheduled production worker can update this dashboard after the site is published and its callback route is activated.", priority: "Normal", isRead: 0 },
  ]);
}

export { MASTER_PROMPT };
