"""Creative queue — the bot/session bridge.

The queue is the one place the 24/7 bot hands work to a live session, so the
contract that matters is: a queued item must be generatable on its own, and
nothing here may ever spend money.
"""

from __future__ import annotations

import json
import pytest

from utils import creative_queue as cq


@pytest.fixture(autouse=True)
def _isolate(tmp_path, monkeypatch):
    """Point the queue at a temp file so tests never touch the real pool."""
    monkeypatch.setattr(cq, "_FILE", tmp_path / "creative_queue.json")
    yield


def test_add_returns_pending_item_with_id():
    item = cq.add("video", "ZYNTH", "The Room", "A single chair in a pool of light.")
    assert item["status"] == "pending"
    assert item["id"] and len(item["id"]) == 12
    assert item["kind"] == "video"
    assert item["resolved_at"] is None


def test_rejects_unknown_kind():
    with pytest.raises(ValueError, match="unknown kind"):
        cq.add("hologram", "ZYNTH", "t", "p")


def test_rejects_empty_prompt():
    """A queued job with no prompt cannot be generated by the draining session."""
    with pytest.raises(ValueError, match="prompt is required"):
        cq.add("image", "ZYNTH", "t", "   ")


def test_pending_filters_by_kind_and_brand():
    cq.add("video", "ZYNTH", "a", "p1")
    cq.add("image", "Dry Fry", "b", "p2")
    cq.add("image", "ZYNTH", "c", "p3")

    assert len(cq.pending()) == 3
    assert len(cq.pending(kind="image")) == 2
    assert len(cq.pending(brand="zynth")) == 2          # case-insensitive
    assert len(cq.pending(kind="image", brand="ZYNTH")) == 1


def test_resolve_moves_item_out_of_pending():
    item = cq.add("scene3d", "ZYNTH", "AURUM", "A ballroom with a curved LED wall.")
    assert cq.resolve(item["id"], "generated", "out/aurum.glb") is True

    assert cq.pending() == []
    counts = cq.counts()
    assert counts["pending"] == 0 and counts["generated"] == 1


def test_resolve_unknown_id_returns_false():
    assert cq.resolve("deadbeef0000", "generated") is False


def test_resolve_rejects_pending_as_target_status():
    item = cq.add("image", "ZYNTH", "t", "p")
    with pytest.raises(ValueError):
        cq.resolve(item["id"], "pending")


def test_counts_breaks_down_by_kind():
    cq.add("image", "ZYNTH", "a", "p")
    cq.add("image", "ZYNTH", "b", "p")
    cq.add("video", "ZYNTH", "c", "p")
    c = cq.counts()
    assert c["image"] == 2 and c["video"] == 1 and c["scene3d"] == 0
    assert c["pending"] == 3


def test_export_carries_the_prompt_so_a_session_needs_no_context():
    cq.add(
        "video", "Dry Fry", "Hear the Crunch",
        "Macro shot of golden crust breaking, 100mm, slow motion.",
        notes="no Burmese in-frame", spec={"duration_s": 5},
    )
    block = cq.export_for_session()
    assert "Macro shot of golden crust" in block
    assert "Dry Fry" in block
    assert "duration_s" in block


def test_export_can_be_narrowed_to_one_kind():
    cq.add("video", "ZYNTH", "v", "video prompt")
    cq.add("image", "ZYNTH", "i", "image prompt")
    only_video = cq.export_for_session(kinds=["video"])
    assert "video prompt" in only_video
    assert "image prompt" not in only_video


def test_empty_queue_messages_are_safe():
    assert "empty" in cq.export_for_session().lower()
    assert "empty" in cq.summary_lines()[0].lower()


def test_pending_items_are_never_trimmed(monkeypatch):
    """Finished items are capped, but pending work must never be silently dropped."""
    monkeypatch.setattr(cq, "_MAX_KEPT", 5)
    for i in range(12):
        cq.add("image", "ZYNTH", f"pending-{i}", "p")
    done = [cq.add("image", "ZYNTH", f"done-{i}", "p") for i in range(12)]
    for d in done:
        cq.resolve(d["id"], "generated")

    assert len(cq.pending()) == 12          # every pending item survived
    stored = json.loads(cq._FILE.read_text())
    assert sum(1 for i in stored if i["status"] == "generated") == 5


def test_corrupt_file_does_not_crash_the_bot():
    cq._FILE.parent.mkdir(parents=True, exist_ok=True)
    cq._FILE.write_text("{ not json")
    assert cq.pending() == []
    assert cq.add("image", "ZYNTH", "t", "p")["status"] == "pending"


def test_new_switches_are_registered_and_default_off():
    from utils import switches
    keys = {k for k, _, _, _ in switches.SWITCHES}
    assert {"brand_creative", "creative_prep"} <= keys
    defaults = {k: d for k, _, _, d in switches.SWITCHES}
    assert defaults["brand_creative"] is False
    assert defaults["creative_prep"] is False
