"""Tablet-first founder command centre for the live Railway dashboard.

The interface is intentionally dependency-free: it uses the dashboard's existing
JSON state and safe APIs, renders quickly on an iPad, and never turns a draft
or internal signal into an external action without a recorded approval.
"""
from __future__ import annotations

import json
from typing import Any


def render(state: dict[str, Any]) -> str:
    state_json = json.dumps(state, ensure_ascii=False).replace("</", "<\\/")
    return _APP.replace("__STATE__", state_json)


_APP = r"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>ZYNTH Founder Command</title>
<style>
:root{--bg:#071014;--surface:#0c171c;--surface2:#101e24;--line:#20333b;--ink:#f1f6f4;--mut:#93a5a8;--cyan:#49d6dc;--cyan2:#0f7984;--gold:#d5ad57;--good:#55c98c;--warn:#f0ba61;--bad:#f07c73;--purple:#a997ed}
*{box-sizing:border-box} html{scroll-behavior:smooth} body{margin:0;background:radial-gradient(900px 530px at 97% -12%,rgba(73,214,220,.13),transparent 65%),radial-gradient(700px 440px at -15% 48%,rgba(213,173,87,.07),transparent 68%),var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.4} button,input,select{font:inherit} button{touch-action:manipulation} .shell{max-width:1440px;margin:auto;padding:0 20px 56px}.top{position:sticky;top:0;z-index:40;display:flex;align-items:center;gap:20px;padding:15px 0 13px;background:linear-gradient(180deg,rgba(7,16,20,.96),rgba(7,16,20,.78));backdrop-filter:blur(16px);border-bottom:1px solid rgba(32,51,59,.8)}.mark{width:38px;height:38px;border:1px solid rgba(73,214,220,.55);border-radius:12px;display:grid;place-items:center;color:var(--cyan);font-weight:800;box-shadow:0 0 30px rgba(73,214,220,.16)}.brand{display:flex;align-items:center;gap:10px;white-space:nowrap}.brand b{display:block;letter-spacing:.15em;font-size:13px}.brand small{display:block;color:var(--mut);font-size:9px;letter-spacing:.15em;margin-top:2px}.nav{display:flex;gap:2px;overflow:auto;flex:1}.nav a{color:var(--mut);text-decoration:none;padding:8px 10px;border-radius:8px;font-size:12px;white-space:nowrap}.nav a:hover{color:var(--ink);background:rgba(255,255,255,.05)}.live{display:flex;gap:6px;align-items:center;color:var(--mut);font-size:11px;white-space:nowrap}.pulse{width:8px;height:8px;border-radius:50%;background:var(--good);box-shadow:0 0 0 5px rgba(85,201,140,.11)}.pulse.warn{background:var(--warn);box-shadow:0 0 0 5px rgba(240,186,97,.11)}.pulse.bad{background:var(--bad);box-shadow:0 0 0 5px rgba(240,124,115,.11)}
.hero{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(260px,.65fr);gap:16px;padding:26px 0 16px}.eyebrow{font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--cyan);font-weight:700}.hero h1{font-size:clamp(28px,4vw,48px);line-height:1.02;letter-spacing:-.045em;margin:9px 0 11px}.hero h1 em{font-style:normal;color:var(--gold)}.hero p{margin:0;color:var(--mut);max-width:670px;font-size:14px}.truth{background:linear-gradient(140deg,rgba(73,214,220,.12),rgba(16,30,36,.9));border:1px solid rgba(73,214,220,.25);border-radius:16px;padding:18px}.truth h3{margin:0 0 10px;font-size:13px}.truth p{font-size:12px;line-height:1.55}.truth .fresh{display:flex;justify-content:space-between;gap:10px;padding-top:12px;border-top:1px solid rgba(255,255,255,.08);font-size:10px;color:var(--mut);margin-top:14px}.truth .fresh b{color:var(--cyan);font-weight:600}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:22px}.stat{background:rgba(12,23,28,.9);border:1px solid var(--line);border-radius:13px;padding:13px 14px;min-height:94px}.stat .k{font-size:10px;color:var(--mut);letter-spacing:.12em;text-transform:uppercase}.stat b{display:block;font-size:28px;line-height:1;margin-top:10px;letter-spacing:-.04em}.stat .sub{display:block;font-size:11px;color:var(--mut);margin-top:6px}.stat.decision{border-color:rgba(240,186,97,.42);background:linear-gradient(130deg,rgba(240,186,97,.12),rgba(12,23,28,.9))}.stat.decision b{color:var(--warn)}.stat.creative b{color:var(--gold)}
.section{margin-top:28px;scroll-margin-top:76px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:0 0 10px}.section-head h2{font-size:18px;margin:0;letter-spacing:-.025em}.section-head p{margin:3px 0 0;color:var(--mut);font-size:11px}.smallbtn,.action{border:1px solid var(--line);color:var(--ink);background:var(--surface2);border-radius:8px;padding:8px 10px;cursor:pointer;font-size:11px}.smallbtn:hover,.action:hover{border-color:var(--cyan)}.card{background:rgba(12,23,28,.88);border:1px solid var(--line);border-radius:14px;padding:15px}.grid2{display:grid;grid-template-columns:1.08fr .92fr;gap:14px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.approval{display:flex;gap:12px;align-items:flex-start;padding:13px 0;border-top:1px solid var(--line)}.approval:first-child{border-top:0;padding-top:1px}.icon{width:34px;height:34px;border-radius:10px;background:rgba(240,186,97,.12);color:var(--warn);display:grid;place-items:center;flex:none}.approval main{min-width:0;flex:1}.approval h3,.creative h3,.project h3{font-size:13px;margin:0 0 3px;line-height:1.3}.meta{font-size:10.5px;color:var(--mut);line-height:1.5}.row{display:flex;align-items:center;justify-content:space-between;gap:9px;flex-wrap:wrap}.badges{display:flex;gap:5px;flex-wrap:wrap}.badge{font-size:9.5px;letter-spacing:.06em;text-transform:uppercase;border:1px solid var(--line);color:var(--mut);padding:3px 6px;border-radius:5px}.badge.pending{color:var(--warn);border-color:rgba(240,186,97,.35)}.badge.internal{color:var(--cyan);border-color:rgba(73,214,220,.28)}.badge.ready{color:var(--good);border-color:rgba(85,201,140,.3)}.badge.review{color:var(--purple);border-color:rgba(169,151,237,.32)}.buttons{display:flex;gap:6px;margin-top:9px}.primary{background:var(--gold);color:#111818;border:0;border-radius:7px;font-weight:750;padding:7px 10px;cursor:pointer;font-size:11px}.primary:hover{filter:brightness(1.07)}.quiet{background:transparent;color:var(--mut);border:1px solid var(--line);border-radius:7px;padding:7px 10px;cursor:pointer;font-size:11px}.quiet:hover{color:var(--ink);border-color:var(--mut)}.empty{font-size:12px;color:var(--mut);padding:14px 0}.notice{border-left:3px solid var(--cyan);padding:10px 12px;background:rgba(73,214,220,.05);border-radius:0 8px 8px 0;color:#bbd1d1;font-size:12px;line-height:1.55}.notice b{color:var(--cyan)}
.creative{position:relative;overflow:hidden;min-height:214px;display:flex;flex-direction:column}.creative:before{content:"";position:absolute;inset:0 0 auto;height:3px;background:linear-gradient(90deg,var(--cyan),var(--gold));opacity:.9}.creative .index{font-size:10px;color:var(--gold);letter-spacing:.14em;margin:5px 0 18px}.creative .theme{font-size:11.5px;line-height:1.55;color:#cfdddb;flex:1}.creative .foot{padding-top:13px;margin-top:12px;border-top:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:5px}.queue{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.q{border:1px solid var(--line);border-radius:10px;padding:11px;background:var(--surface2)}.q b{font-size:19px;letter-spacing:-.04em;display:block;color:var(--gold)}.q span{font-size:10px;color:var(--mut)}.qlist{margin-top:11px}.qitem{border-top:1px solid var(--line);padding:9px 0;font-size:12px}.qitem:first-child{border-top:0}.qitem strong{display:block;font-size:12px;line-height:1.35}.qitem small{color:var(--mut);font-size:10px}.project-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.project{padding:13px}.stage{font-size:9.5px;letter-spacing:.11em;text-transform:uppercase;color:var(--cyan)}.project h3{margin-top:7px}.project .number{font-size:17px;color:var(--gold);letter-spacing:-.03em;margin-top:10px}.project .statusline{height:4px;background:var(--surface2);border-radius:8px;margin-top:12px;overflow:hidden}.project .statusline i{display:block;height:100%;background:linear-gradient(90deg,var(--cyan2),var(--cyan));width:25%}.project select{width:100%;margin-top:10px;background:#0a1317;color:var(--ink);border:1px solid var(--line);border-radius:7px;padding:7px;font-size:11px}.source{font-size:9.5px;color:var(--mut);display:flex;align-items:center;gap:5px}.source i{width:6px;height:6px;border-radius:50%;display:inline-block;background:var(--cyan)}
.command-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.command{border:1px solid var(--line);background:var(--surface2);border-radius:11px;text-align:left;padding:12px;cursor:pointer;color:var(--ink);min-height:82px}.command:hover{border-color:var(--cyan);transform:translateY(-1px)}.command .tag{font-size:9px;letter-spacing:.13em;color:var(--cyan);text-transform:uppercase}.command b{font-size:12px;display:block;margin-top:7px}.command span{display:block;color:var(--mut);font-size:10px;margin-top:3px}.systems{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.system{border:1px solid var(--line);border-radius:10px;padding:11px;background:var(--surface2);display:flex;justify-content:space-between;align-items:start;gap:8px}.system b{font-size:12px}.system small{display:block;font-size:10px;color:var(--mut);margin-top:3px;line-height:1.4}.dot{width:8px;height:8px;border-radius:50%;margin-top:4px;background:var(--mut);flex:none}.dot.good{background:var(--good)}.dot.warn{background:var(--warn)}.dot.bad{background:var(--bad)}.switches{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.switch{display:flex;align-items:center;justify-content:space-between;border:1px solid var(--line);border-radius:9px;padding:9px 10px;background:var(--surface2);font-size:11px}.switch span{color:var(--mut);max-width:72%;overflow:hidden;text-overflow:ellipsis}.switch button{border:1px solid var(--line);background:#0a1317;color:var(--mut);font-size:9px;letter-spacing:.09em;padding:4px 8px;border-radius:5px;cursor:pointer}.switch button.on{background:rgba(85,201,140,.16);border-color:rgba(85,201,140,.34);color:var(--good)}.toast{position:fixed;z-index:70;left:50%;bottom:22px;transform:translate(-50%,18px);opacity:0;background:#d9f6ef;color:#08211e;padding:10px 14px;border-radius:9px;font-weight:700;font-size:12px;transition:.2s;pointer-events:none}.toast.on{opacity:1;transform:translate(-50%,0)}.modalback{position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:60;display:none}.modalback.show{display:block}.modal{position:fixed;z-index:61;right:18px;top:72px;width:min(540px,calc(100vw - 36px));max-height:calc(100vh - 90px);overflow:auto;background:#0b151a;border:1px solid var(--line);border-radius:15px;padding:18px;box-shadow:0 30px 90px rgba(0,0,0,.5);display:none}.modal.show{display:block}.modal h2{font-size:18px;margin:2px 0 8px}.modal pre{white-space:pre-wrap;font-family:inherit;font-size:12px;line-height:1.6;color:#c9d8d6}.close{float:right;background:transparent;border:0;color:var(--mut);font-size:20px;cursor:pointer}.hide{display:none!important}
@media(max-width:840px){.shell{padding:0 14px 44px}.top{gap:10px}.nav{order:3;width:100%;padding-bottom:1px}.live{margin-left:auto}.hero{grid-template-columns:1fr;padding-top:18px}.stats{grid-template-columns:repeat(2,1fr)}.grid2,.grid3{grid-template-columns:1fr}.command-grid{grid-template-columns:repeat(2,1fr)}.project-grid{grid-template-columns:1fr}.truth{display:none}.section{margin-top:22px}.top{padding-top:calc(12px + env(safe-area-inset-top))}.hero h1{font-size:34px}.creative{min-height:185px}}
</style></head><body><div class="shell">
<header class="top"><div class="brand"><div class="mark">Z</div><div><b>ZYNTH COMMAND</b><small>FOUNDER OPERATING SYSTEM</small></div></div><nav class="nav"><a href="#today">Today</a><a href="#approvals">Approvals</a><a href="#creative">Creative Studio</a><a href="#projects">Projects</a><a href="#intelligence">Intelligence</a><a href="#system">System</a></nav><div class="live"><i class="pulse"></i><span id="syncText">LIVE</span></div></header>
<main>
<section class="hero" id="today"><div><div class="eyebrow" id="day">Founder view</div><h1>Make the next <em>right decision.</em></h1><p>One clear place for ZYNTH’s verified work, internal creative intelligence, and the approvals that only you can make.</p></div><aside class="truth"><h3>Information integrity</h3><p>This command centre separates confirmed records from internal hypotheses. It does not convert research, concepts, or queued production into a client commitment.</p><div class="fresh"><span>Last refreshed</span><b id="fresh">—</b></div></aside></section>
<section class="stats" id="stats"></section>
<section class="section" id="approvals"><div class="section-head"><div><h2>Decisions waiting for you</h2><p>Only real projects that need a recorded founder decision appear here.</p></div><button class="smallbtn" onclick="refresh()">Refresh data</button></div><div class="grid2"><div class="card" id="approvalList"></div><div class="card"><div class="eyebrow">Your operating focus</div><div id="directives" style="margin-top:11px"></div><div class="notice" style="margin-top:14px"><b>Safe by design.</b> Internal proposals and creative jobs remain drafts until you approve a linked project. Nothing here sends to a client, spends money, books a vendor, publishes, or releases paid media.</div></div></div></section>
<section class="section" id="creative"><div class="section-head"><div><h2>Daily Creative Studio</h2><p>Internal proposal intelligence, ready for your selection and direction.</p></div><button class="smallbtn" onclick="document.getElementById('projects').scrollIntoView()">View project work</button></div><div class="grid3" id="creativeCards"></div><div class="grid2" style="margin-top:14px"><div class="card"><div class="row"><div><div class="eyebrow">Production queue</div><h3 style="margin:5px 0 0;font-size:16px">Creative work, controlled</h3></div><span class="badge review">Founder route</span></div><div class="queue" id="queueCounts" style="margin-top:13px"></div><div class="qlist" id="queueList"></div></div><div class="card"><div class="eyebrow">Creative standard</div><h3 style="font-size:16px;margin:5px 0 8px">Concept → proof → production</h3><p class="meta" style="font-size:12px;line-height:1.6">Every material idea is evaluated for strategy, originality, brand/craft, feasibility, commercial logic, measurement, and risk before external release.</p><div class="badges" style="margin-top:13px"><span class="badge internal">3 creative territories</span><span class="badge ready">quality gate 4/5+</span><span class="badge review">human release</span></div></div></div></section>
<section class="section" id="projects"><div class="section-head"><div><h2>Project portfolio</h2><p>Live records, stage health, commercial value, and founder approval state.</p></div><button class="smallbtn" onclick="openNewProject()">+ New founder project</button></div><div class="project-grid" id="projectGrid"></div></section>
<section class="section" id="intelligence"><div class="section-head"><div><h2>Agency intelligence</h2><p>Real pipeline, proposal factory, research signals, and system learning.</p></div></div><div class="grid2"><div class="card"><div class="eyebrow">Pipeline</div><div id="pipeline" style="margin-top:10px"></div></div><div class="card"><div class="eyebrow">Proposal factory</div><div id="proposalList" style="margin-top:10px"></div></div></div></section>
<section class="section" id="system"><div class="section-head"><div><h2>Command Deck & safeguards</h2><p>Queue internal work, check connection health, and keep autonomy under your control.</p></div></div><div class="grid2"><div class="card"><div class="command-grid" id="commands"></div><div class="source" style="margin-top:12px"><i></i> Commands queue approved internal workflow requests; they do not send external communication.</div></div><div class="card"><div class="row"><div><div class="eyebrow">Automation mode</div><h3 style="font-size:16px;margin:5px 0 0" id="autonomyTitle">—</h3></div><button class="smallbtn" id="modeBtn" onclick="toggleMode()">—</button></div><div class="switches" id="switches" style="margin-top:14px"></div></div></div><div class="card" style="margin-top:14px"><div class="eyebrow">System Vitals · connection health</div><div class="systems" id="systems" style="margin-top:11px"></div></div></section>
</main></div><div class="modalback" id="back" onclick="closeModal()"></div><aside class="modal" id="modal"></aside><div class="toast" id="toast"></div>
<script>
let S=__STATE__; const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])); const money=n=>n?new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n):'—';
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('on');setTimeout(()=>x.classList.remove('on'),2500)}
async function api(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Request could not be completed');return j}
function truthFor(row){if(row?.founder_approval==='approved'||row?.source==='dashboard'||row?.source==='md'||row?.source==='owner')return ['FOUNDER RECORD','ready'];if(row?.founder_approval==='pending')return ['NEEDS CONFIRMATION','pending'];return ['INTERNAL / REVIEW','internal']}
function stageProgress(s){return ({lead:16,proposal:36,won:68,delivery:84,done:100,lost:100})[s]||12}
function render(){const d=new Date(),health=String(S.connections?.overall||'ok').toLowerCase(),label=health==='down'?'CHECKS NEED ATTENTION':health==='warn'?'CHECKS NEED REVIEW':'LIVE DATA';$('#day').textContent=d.toLocaleDateString('en-SG',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();$('#fresh').textContent=S.generated||'Live state';$('#syncText').textContent=label;$('.pulse').className='pulse '+(health==='down'?'bad':health==='warn'?'warn':'');renderStats();renderApprovals();renderCreative();renderProjects();renderIntelligence();renderSystem()}
function renderStats(){const ps=S.project_summary||{},q=S.queue||{},pending=approvals().length;$('#stats').innerHTML=`<div class="stat decision"><span class="k">Decisions waiting</span><b>${pending}</b><span class="sub">Founder approval needed</span></div><div class="stat"><span class="k">Active projects</span><b>${ps.active||0}</b><span class="sub">${ps.total||0} in total portfolio</span></div><div class="stat"><span class="k">Pipeline value</span><b>${money(ps.pipeline_mmk)}<small style="font-size:11px;color:var(--mut)"> MMK</small></b><span class="sub">${money(ps.expected_mmk)} MMK weighted</span></div><div class="stat creative"><span class="k">Creative queue</span><b>${q.pending||0}</b><span class="sub">${q.image||0} image · ${q.video||0} video · ${q.scene3d||0} 3D</span></div>`}
function approvals(){return (S.projects||[]).filter(p=>p.founder_confirmation_required&&p.founder_approval==='pending')}
function renderApprovals(){const a=approvals(),direct=S.directives||[];$('#approvalList').innerHTML=a.length?a.map(p=>`<article class="approval"><div class="icon">!</div><main><div class="row"><div><h3>${esc(p.name)}</h3><div class="meta">${esc(p.client||'No client named')} · ${esc(p.kind||'project')} · ${esc(p.market||'')}</div></div><span class="badge pending">Founder confirmation</span></div><div class="meta" style="margin-top:6px">${esc(p.notes||'Internal/agent-discovered project. Confirm only if you want ZYNTH to begin a real proposal or delivery workflow.')}</div><div class="buttons"><button class="primary" onclick="decide('${esc(p.id)}','approve')">Approve project</button><button class="quiet" onclick="decide('${esc(p.id)}','decline')">Decline</button></div></main></article>`).join(''):`<div class="empty">No real projects are awaiting confirmation. Your internal research and proposal factory can continue safely in Explore mode.</div>`;$('#directives').innerHTML=direct.length?direct.map((x,i)=>`<div class="approval"><div class="icon" style="background:rgba(73,214,220,.1);color:var(--cyan)">${i+1}</div><main><h3>${esc(x)}</h3><div class="meta">Generated from current system state · review before taking external action</div></main></div>`).join(''):`<div class="empty">No immediate directives. Review Creative Studio or add a founder project.</div>`}
async function decide(id,action){if(!confirm(action==='approve'?'Confirm this project may move into a real proposal/delivery workflow?':'Decline this project record?'))return;try{await api('/api/project',{action,id,approved_by:'MD'});toast(action==='approve'?'Project approved and recorded':'Project declined and recorded');await refresh()}catch(e){toast(e.message)}}
function renderCreative(){const p=(S.deliverables||[]).slice(0,3);$('#creativeCards').innerHTML=p.length?p.map((x,i)=>`<article class="card creative"><div class="index">0${i+1} · INTERNAL CONCEPT</div><h3>${esc(x.title)}</h3><div class="theme">${esc(x.meta||'Proposal Factory concept')}<br><span class="meta">Use this as an internal creative territory. Select a direction before commissioning external work.</span></div><div class="foot"><span class="badge internal">${esc(x.type||'proposal')}</span><button class="smallbtn" onclick="openProposal('${esc(x.title)}')">Review</button></div></article>`).join(''):`<div class="card empty">No proposal packages are available yet. Queue the daily workforce when you are ready.</div>`;const q=S.queue||{};$('#queueCounts').innerHTML=[['Image',q.image||0],['Video',q.video||0],['3D scenes',q.scene3d||0]].map(([n,v])=>`<div class="q"><b>${v}</b><span>${n}</span></div>`).join('');const jobs=S.creative_jobs||[];$('#queueList').innerHTML=jobs.length?jobs.map(j=>`<div class="qitem"><strong>${esc(j.title)}</strong><small>${esc(j.kind)} · ${esc(j.brand||'ZYNTH')} · prepared internally · ${esc(j.approval_state||'review required')}</small></div>`).join(''):`<div class="empty">No production jobs are waiting. Prepared jobs will appear here after a reviewed concept is routed to production.</div>`}
function renderProjects(){const rows=(S.projects||[]).filter(p=>p.stage!=='done'&&p.stage!=='lost').slice(0,8);$('#projectGrid').innerHTML=rows.length?rows.map(p=>{const[t,c]=truthFor(p);return `<article class="card project"><div class="row"><span class="stage">${esc(p.stage)}</span><span class="badge ${c}">${t}</span></div><h3>${esc(p.name)}</h3><div class="meta">${esc(p.client||'Internal ZYNTH')} · ${esc(p.kind)} · ${esc(p.market)}</div><div class="number">${p.value_mmk?money(p.value_mmk)+' MMK':'Value not set'}</div><div class="statusline"><i style="width:${stageProgress(p.stage)}%"></i></div><select onchange="moveProject('${esc(p.id)}',this.value)"><option value="">Move stage…</option>${['lead','proposal','won','delivery','done','lost'].filter(s=>s!==p.stage).map(s=>`<option value="${s}">${s}</option>`).join('')}</select><div class="source" style="margin-top:9px"><i></i>${esc(p.source||'project')} · ${p.event_date?'hard date '+esc(p.event_date):'no hard date'}</div></article>`}).join(''):`<div class="card empty">No active project records yet. Add a founder-owned project to begin with a verified scope and approval path.</div>`}
async function moveProject(id,stage){if(!stage)return;try{await api('/api/project',{action:'stage',id,stage});toast('Project stage updated');await refresh()}catch(e){toast(e.message);await refresh()}}
function renderIntelligence(){const pipe=S.pipeline||[],max=Math.max(1,...pipe.map(x=>x.count||0));$('#pipeline').innerHTML=pipe.map(x=>`<div style="margin:10px 0"><div class="row"><span style="font-size:12px;text-transform:capitalize">${esc(x.stage)}</span><span class="meta">${x.count} · ${x.value?'S$'+money(x.value):'no value recorded'}</span></div><div style="height:5px;background:var(--surface2);border-radius:8px;margin-top:5px"><i style="display:block;height:100%;width:${Math.round((x.count||0)/max*100)}%;background:var(--cyan);border-radius:8px"></i></div></div>`).join('')||'<div class="empty">No live lead records.</div>';const p=S.deliverables||[];$('#proposalList').innerHTML=p.length?p.slice(0,6).map(x=>`<div class="qitem"><strong>${esc(x.title)}</strong><small>${esc(x.meta||'Internal proposal')} · ${esc(x.date||'date not recorded')}</small></div>`).join(''):'<div class="empty">No proposal library entries.</div>'}
function renderSystem(){const C=[['CEO brief','brief','Daily strategic brief'],['Prospect scout','research','Research priority accounts'],['Proposal factory','proposals','Create internal proposals'],['Creative workforce','workforce','Prepare 3 creative packages'],['Cost audit','costaudit','Review AI-spend evidence'],['Improve system','improve','Run internal learning review'],['Sync knowledge','push','Refresh founder knowledge vault'],['Consolidate','consolidation','Housekeep operations records']];$('#commands').innerHTML=C.map(([a,k,d])=>`<button class="command" onclick="command('${k}')"><span class="tag">Queue</span><b>${a}</b><span>${d}</span></button>`).join('');const on=!S.md_only;$('#autonomyTitle').textContent=on?'Autonomy awake':'MD-only mode';const b=$('#modeBtn');b.textContent=on?'Set MD-only':'Wake internal work';b.style.color=on?'var(--warn)':'var(--good)';const sw=(S.switches||[]).filter(x=>!x.master);$('#switches').innerHTML=sw.map(x=>`<div class="switch"><span>${esc(x.name)}</span><button class="${x.on?'on':''}" onclick="toggle('${esc(x.name)}',${x.on?1:0})">${x.on?'ON':'OFF'}</button></div>`).join('')||'<div class="empty">No switches available.</div>';const links=S.connections?.links||[];$('#systems').innerHTML=links.length?links.map(x=>`<div class="system"><div><b>${esc(x.name||x.key)}</b><small>${esc(x.detail||'No detail')}</small></div><i class="dot ${esc(x.status||'warn')}"></i></div>`).join(''):'<div class="empty">Connection health unavailable.</div>'}
async function command(cmd){try{await api('/api/cmd',{cmd});toast('Internal workflow queued: '+cmd)}catch(e){toast(e.message)}} async function toggle(name,on){try{await api('/api/switch',{name,on:!on});toast(name+' updated');await refresh()}catch(e){toast(e.message)}}async function toggleMode(){try{await api('/api/switch',{name:'autonomy',on:!!S.md_only});toast(S.md_only?'Internal work awakened':'MD-only mode set');await refresh()}catch(e){toast(e.message)}}
function openNewProject(){openModal(`<button class="close" onclick="closeModal()">×</button><div class="eyebrow">Founder project</div><h2>Create a verified project record</h2><p class="meta">Projects added here are recorded as founder-created. This does not send a proposal or commit external activity.</p><div style="display:grid;gap:9px;margin-top:14px"><input id="newName" placeholder="Project name" style="padding:10px;background:#091217;border:1px solid var(--line);border-radius:8px;color:var(--ink)"><input id="newClient" placeholder="Client or internal ZYNTH" style="padding:10px;background:#091217;border:1px solid var(--line);border-radius:8px;color:var(--ink)"><div style="display:flex;gap:8px"><select id="newKind" style="flex:1;padding:10px;background:#091217;border:1px solid var(--line);border-radius:8px;color:var(--ink)"><option value="campaign">Campaign</option><option value="event">Event</option><option value="video">Video</option><option value="social">Social</option><option value="stage_design">Stage design</option><option value="sponsorship">Sponsorship</option></select><select id="newMarket" style="flex:1;padding:10px;background:#091217;border:1px solid var(--line);border-radius:8px;color:var(--ink)"><option>MM</option><option>SG</option></select></div><button class="primary" onclick="createProject()">Create founder project</button></div>`) }
async function createProject(){try{const name=$('#newName').value.trim();if(!name)throw Error('A project name is required');await api('/api/project',{action:'add',name,client:$('#newClient').value,kind:$('#newKind').value,market:$('#newMarket').value,source:'dashboard'});closeModal();toast('Founder project created');await refresh()}catch(e){toast(e.message)}}
async function openProposal(title){try{const r=await api('/api/proposals',{action:'list',q:title});const x=(r.items||[])[0];if(!x){openModal('<button class="close" onclick="closeModal()">×</button><h2>Proposal</h2><p class="meta">This internal proposal is listed in the factory but its detailed document is not available in this deployment.</p>');return}const d=await api('/api/proposals',{action:'open',id:x.id||x.slug||x.title});openModal(`<button class="close" onclick="closeModal()">×</button><div class="eyebrow">Internal proposal · review only</div><h2>${esc(d.proposal?.title||title)}</h2><pre>${esc(JSON.stringify(d.proposal||d,null,2))}</pre>`)}catch(e){openModal(`<button class="close" onclick="closeModal()">×</button><h2>${esc(title)}</h2><p class="meta">${esc(e.message)}</p>`)} }
function openModal(html){$('#modal').innerHTML=html;$('#back').classList.add('show');$('#modal').classList.add('show')}function closeModal(){$('#back').classList.remove('show');$('#modal').classList.remove('show')}async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store'});const n=await r.json();if(n.error)throw Error(n.error);S=n;render()}catch(e){toast('Live refresh unavailable: '+e.message)}}render();setInterval(refresh,20000);
</script></body></html>"""
